#pragma once
#include <cstdint>

// Upload this file to https://gurp.cc/otherOffsets.h
// Generated by tools/dump_other_offsets.py at 2026-08-17 13:22 UTC

namespace Offsets {
    inline std::string ClientVersion = "version-ddf602d9cfe44005";

    namespace Attribute {
         inline constexpr uintptr_t TypeIdRva = 0x867113C;
    }

    namespace FastClusterEntity {
         inline constexpr uintptr_t VTableRva = 0x68CB818;
         inline constexpr uintptr_t RenderQueueId = 0x10;
         inline constexpr uintptr_t TechniqueArrayPtr = 0x70;
    }

    namespace TechniqueArray {
         inline constexpr uintptr_t BeginOffset = 0x0;
         inline constexpr uintptr_t EndOffset = 0x8;
    }

    namespace MaterialLayer {
         inline constexpr uintptr_t Stride = 136;
         inline constexpr uintptr_t FillModeByte = 0x11;
         inline constexpr uintptr_t MatFlags = 0x18;
         inline constexpr uintptr_t Param = 0x1C;
         inline constexpr uintptr_t Flags2 = 0x20;
         inline constexpr uintptr_t ColorData = 0x24;
    }

    namespace WorldRoot {
         inline constexpr uintptr_t BoundFnOffset = 0x80;
         inline constexpr uintptr_t RaycastDescriptorRva = 0x0;
         inline constexpr uintptr_t FindPartOnRayDescriptorRva = 0x0;
         inline constexpr uintptr_t FindPartOnRayWithIgnoreListDescriptorRva = 0x0;
         inline constexpr uintptr_t FindPartOnRayWithWhitelistDescriptorRva = 0x0;
         inline constexpr uintptr_t RaycastCachedTerrainDescriptorRva = 0x0;
         inline constexpr uintptr_t RaycastBatchedDescriptorRva = 0x0;
         inline constexpr uintptr_t RaycastTerrainDescriptorRva = 0x0;
    }
}
