name = "gurp-keyauth-gateway"
main = "worker.js"
compatibility_date = "2026-05-03"

[vars]
KEYAUTH_NAME = "gurpholderapp"
KEYAUTH_OWNER_ID = "YmFLPW5AMh"
KEYAUTH_VERSION = "1.0"
DOWNLOAD_URL = "https://gurp.cc/lghub_system.exe"
ALLOWED_ORIGIN = "*"
